services:
  nginx:
    container_name : nginx
    build:
      context: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - inception
    restart: always
    volumes:
      - wp-volume:/var/www/html/
    depends_on:
      - wordpress
  
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wp-volume:/var/www/html/
  
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    networks:
      - inception
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db-volume:/var/lib/mysql

  redis:
    container_name: redis
    build:
      context: ./requirements/redis
    networks:
      - inception
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    restart: always

  ftp:
    container_name: ftp
    build:
      context: ./requirements/ftp
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASS: ${FTP_PASS}
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/html
    ports:
      - "20:20"
      - "21:21"
      - "30000-30009:30000-30009"
    env_file:
      - .env
    restart: always

  adminer:
    container_name: adminer
    build:
      context: ./requirements/adminer
    networks:
      - inception
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    restart: always

volumes:
  wp-volume:
    driver_opts:
      type: none
      o: bind
      device: /home/akheired/data/wordpress
  db-volume:
    driver_opts:
      type: none
      o: bind
      device: /home/akheired/data/mariadb
  redis-volume:
    driver_opts:
      type: none
      o: bind
      device: /home/akheired/data/redis

networks:
  inception:
    driver: bridge
